import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/_component/context/ContextProvider";

// Configuración de fuentes de Google
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadatos de la aplicación (SEO)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout Principal (RootLayout)
// Envuelve a todas las páginas de la aplicación
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Envoltura con el ContextProvider para dar acceso a React Query en toda la app */}
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
